#!/usr/bin/env bash

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "must be sourced"
    exit 10
fi

if ! command -v python; then 
  echo 'python not installed'
  return 20
fi

if [ -z "$VIRTUAL_ENV_DIR" ]; then
  echo 'using default env directory'
  VIRTUAL_ENV_DIR=.venv
fi

if [ ! -d .venv ]; then
  echo 'initialising virtual env'
  python -m venv "$VIRTUAL_ENV_DIR"  

    if [ -f requirements.txt ]; then
    echo 'installing local requirements'
    "$VIRTUAL_ENV_DIR/bin/pip" install -r requirements.txt
  else
    echo 'no requirements.txt available'
  fi

  ACTIVATE_SCRIPT="$VIRTUAL_ENV_DIR/bin/activate"
  if [ -f "$ACTIVATE_SCRIPT" ]; then
      # shellcheck disable=SC1090
      source "$ACTIVATE_SCRIPT"
  else
      echo "Error: Virtual environment activation script not found at $ACTIVATE_SCRIPT"
      return 30
  fi
fi

