#!/bin/sh

DEFAULT_VENV_DIR=".venv"

if [ $# -eq 0 ]; then
    echo "Virtual environment directory is not set, using default $DEFAULT_VENV_DIR"
    VENV_DIR=$DEFAULT_VENV_DIR
else
    VENV_DIR=$1
fi

if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv $VENV_DIR

    if [ $? -ne 0 ]; then
        echo "Failed to create virtual environment" >&2
        exit 1
    fi

    echo "Virtual environment created at $VENV_DIR"

    $VENV_DIR/bin/pip install -r requirements.txt

    if [ $? -ne 0 ]; then
        echo "Failed to install dependencies" >&2
        exit 1
    fi

    echo "Virtual environment is activated and dependencies are installed."
fi

. $VENV_DIR/bin/activate
